
const login = async(data) => {

        checkIfIsCancelled()

        setLoading(true)
        setError(false)

        try {
            
          await signInWithEmailAndPassword(auth, data.email, data.password)
          setLoading(false)

        } catch (error) {
            
            let systemErrorMessage

             if (error.message.includes("user-not-found")) {
        systemErrorMessage = "Usuário não encontrado.";
      } else if (error.message.includes("wrong-password")) {
        systemErrorMessage = "Senha incorreta.";
      } else {
        systemErrorMessage = "Ocorreu um erro, por favor tenta mais tarde.";
      }

            setError(systemErrorMessage)
            

        }
        setLoading(false)
    }